version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - ${MYSQL_BINDING_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure
